version: "3.9"

services:

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - APP_VERSION=${APP_VERSION}
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      #./prometheus_config:/etc/prometheus:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring

networks:
  monitoring: